# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'UITableView头部悬停问题' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UITableView头部悬停问题
  pod 'Masonry'
  target 'UITableView头部悬停问题Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UITableView头部悬停问题UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
